export const config = {
  botName: process.env.BOT_NAME || 'Elaina MD',
  ownerName: process.env.BOT_OWNER || 'syah-p',
  ownerNumber: process.env.BOT_OWNER_NUMBER || '628xxx',
  prefix: process.env.BOT_PREFIX || '.',
  rateLimit: parseInt(process.env.RATE_LIMIT) || 30,
  debug: process.env.DEBUG === 'true',
};

export const symbols = {
  download: '📥',
  search: '🔍',
  tools: '🛠️',
  sticker: '🎨',
  media: '📸',
  fun: '🎮',
  admin: '⚙️',
  owner: '👑',
  info: 'ℹ️',
  user: '👤',
  group: '👥',
  other: '⭐',
  success: '✅',
  error: '❌',
  wait: '⏳',
  check: '✔️',
  star: '⭐',
  heart: '❤️',
  fire: '🔥',
  rocket: '🚀',
  crown: '👑',
  thunder: '⚡',
  gem: '💎',
  settings: '⚙️',
};
